[package]
name = "share-reg"
version = "0.1.0"
authors = ["jack <jackson.virgo1@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

[lib]
crate-type = ["cdylib"]

[dependencies]
smart-contract = "0.1.0"
smart-contract-macros = "0.1.0"
